name: planit
description:  PLANIT is an e-commerce platform designed for seamless management 
              of products by business administrators, while customers can 
              conveniently make purchases through Android and iOS applications. 
              You can access the platform via the following web link- 
              https://planit.club/. The project has been developed using the 
              Flutter/Bloc Framework.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  auto_route: ^7.9.2
  flutter_bloc: ^8.1.4
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.7
  flutter_svg: ^2.0.9
  flutter_carousel_widget: ^2.2.0
  collection: ^1.16.0
  carousel_slider: ^4.2.1
  flutter_otp_text_field: ^1.1.3+2
  dio: ^5.4.3+1
  skeletonizer: ^1.1.2+1
  dartz: ^0.10.1
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  auto_route_generator: ^7.3.2
  flutter_native_splash : ^2.4.0
  dart_code_metrics: ^5.7.6


flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/json/
    - assets/demo/


flutter_icons:
  image_path: assets/png/splash.png
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#F7F4DE"
  image: assets/png/splash.png
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

  android_12:
    image: assets/png/splash.png
    color: "#F7F4DE"
    fullscreen: true